"""Added vat_exempt_reason

Revision ID: d9ca41483bcf
Revises: a7ab8aabac7c
Create Date: 2026-02-06 18:21:53.576264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ca41483bcf'
down_revision = 'a7ab8aabac7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_exempt_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('vat_exempt_reason')

    # ### end Alembic commands ###
